// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';

export function AddCountdown(arg1:string,arg2:domain.Rule):Promise<string>;

export function CountdownEvents():Promise<Array<main.CountdownView>>;

export function DeleteCountdown(arg1:string):Promise<boolean>;

export function GetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:number,arg2:number):Promise<boolean>;

export function Status():Promise<main.AppStatus>;

export function Timeline():Promise<Array<main.TimelineEntry>>;

export function UpdateCountdown(arg1:string,arg2:string,arg3:domain.Rule):Promise<string>;
