// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {model} from '../models';

export function AddCountdown(arg1:string,arg2:domain.Rule):Promise<string>;

export function AddCounter(arg1:string,arg2:string,arg3:number):Promise<string>;

export function CountdownEvents():Promise<Array<model.CountdownView>>;

export function Counters():Promise<Array<model.CounterView>>;

export function DecrementCounter(arg1:string):Promise<number>;

export function DeleteCountdown(arg1:string):Promise<boolean>;

export function DeleteCounter(arg1:string):Promise<boolean>;

export function GetCardOrder():Promise<Array<string>>;

export function GetSettings():Promise<model.Settings>;

export function IncrementCounter(arg1:string):Promise<number>;

export function SaveCardOrder(arg1:Array<string>):Promise<boolean>;

export function SaveSettings(arg1:number,arg2:number):Promise<boolean>;

export function SetCounterCount(arg1:string,arg2:number):Promise<number>;

export function Status():Promise<model.AppStatus>;

export function Timeline():Promise<Array<model.TimelineEntry>>;

export function UpdateCountdown(arg1:string,arg2:string,arg3:domain.Rule):Promise<string>;

export function UpdateCounter(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;
